# Aplicando Funções

#### Diferença entre os métodos

##### .map() → só funciona em Series (coluna única).

##### .apply() → funciona em linhas ou colunas inteiras (axis=0 colunas, axis=1 linhas).

##### .applymap() → aplica função elemento a elemento em todo o DataFrame.

##### obs: applymap já está depreciado use .map() ao invés de .applymap()

In [30]:
import pandas as pd

In [31]:
littles = pd.DataFrame(
    data=[[3, 5, 3, 5],
          [3, 6, 2, 13],
          [14, 10, 3, 1]],
          index=[1, 2, 3],
          columns=["Mês 1", "Mês 2", "Mês 3", "Mês 4"]
)

In [32]:
# usando .map() com lambda
# multiplicando lambda
df_multi = littles.map(lambda x: x * 10)
df_multi

   Mês 1  Mês 2  Mês 3  Mês 4
1     30     50     30     50
2     30     60     20    130
3    140    100     30     10

In [33]:
# usando lambda(lambda x: valor if (condição)) com if ternário
df_flag = littles.map(lambda x: "Alto" if x > 5 else "Baixo")
df_flag

   Mês 1  Mês 2  Mês 3  Mês 4
1  Baixo  Baixo  Baixo  Baixo
2  Baixo   Alto  Baixo   Alto
3   Alto   Alto  Baixo  Baixo

### Comparação com .apply() por linha ou coluna

In [34]:
# soma de cada linha (axis=1)
linha_soma = littles.apply(lambda row: row.sum(), axis=1)
linha_soma

1    16
2    24
3    28
dtype: int64

In [ ]:
# Média de cada coluna (axis=0)
coluna_media = littles.apply(lambda col: col.mean(), axis=0)
coluna_media

Mês 1    6.666667
Mês 2    7.000000
Mês 3    2.666667
Mês 4    6.333333
dtype: float64

# COPY() recapitulando o tema
#### No pandas, .copy() serve para criar uma cópia independente de um DataFrame ou Series.

#### Sem .copy(), muitas vezes o que você tem é apenas uma referência (um "espelho") do objeto original.

#### Com .copy(), você garante que as alterações não afetam o DataFrame original.